apiVersion: v1
kind: Service
metadata: 
  name: db-service
  labels:
    app: postgres-db
    tier: database
spec: 
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-db
    tier: database
  clusterIP: None