apiVersion: v1
kind: PersistentVolume
metadata: 
  name: postgres-pv-volume
  labels:
    type: local
    app: postgres-db
spec:
  storageClassName: manual
  capacity: 
    storage: 50Mi
  accessModes: 
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: poastgres-db
spec:
  storageClassName: manual
  accessModes: 
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi