spring:

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        # ddl-auto: create
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  data:
    mongodb:
      auto-index-creation: true

  flyway:
    enabled: true

#  Genre Cache Evict Schedule
scheduled:
  initialDelay:
    hours: 4

  fixedDelay:
    hours: 4

# TimeOutTask for parallel enrichment
task:
  timeOut:
    seconds: 5

#  Task Executor Configuration
executor:
  max:
    pool:
      size: 10

  core:
    pool:
      size: 3

  queue:
    capacity: 10

  thread:
    name:
      prefix: "taskExecutor-"