
spring:

      profiles:
          active: dev

      datasource:
          driver-class-name: org.postgresql.Driver

      jpa:
          properties:
              hibernate:
                  ddl-auto: create-drop
                  dialect: org.hibernate.dialect.PostgreSQLDialect
                  format_sql: true

      flyway:
          enabled: true
